package com.kadioglumf.specification.search.exception;

public enum SearchErrorCode {
  INVALID_PAGE,
  INVALID_PAGE_SIZE,
  TOO_MANY_FILTERS,
  UNKNOWN_FIELD,
  FIELD_NOT_FILTERABLE,
  FIELD_NOT_SORTABLE,
  UNSUPPORTED_FILTER_TYPE,
  UNSUPPORTED_OPERATOR,
  INVALID_SORT_ORDER,
  INVALID_VALUE_TYPE,
  INVALID_BOOLEAN,
  INVALID_NUMBER,
  INVALID_DATE,
  EMPTY_VALUE,
  TOO_MANY_IN_VALUES
}
